# -*- coding: utf-8 -*- 
import os 
print("Updating web_app.py...") 
ROUTES = "\n\n# ============== DASHBOARD ==============\n@app.route('/dashboard')\n@login_required\ndef dashboard():\n    stats = db.dashboard_stats(30)\n    top_p = db.top_products(30, 10)\n    top_s = db.top_sellers(30, 10)\n    return render_template('dashboard.html', stats=stats, top_products=top_p, top_sellers=top_s)\n\n\n# ============== KPI ==============\n@app.route('/kpi')\n@login_required\ndef kpi_view():\n    leaderboard = db.kpi_leaderboard(30)\n    return render_template('kpi.html', leaderboard=leaderboard)\n\n\n# ============== ZONES ==============\n@app.route('/zones')\n@login_required\ndef zones_list():\n    zones = db.list_zones()\n    return render_template('zones.html', zones=zones)\n\n\n@app.route('/zones/add', methods=['POST'])\n@login_required\ndef zone_add():\n    name = request.form.get('name', '').strip()\n    if name:\n        db.add_zone(name, float(request.form.get('fee') or 0), float(request.form.get('free_from') or 0), int(request.form.get('eta') or 60))\n        flash('Zone added', 'success')\n    return redirect('/zones')\n\n\n# ============== PRODUCT IMAGES ==============\n@app.route('/product/<int:pid>/images', methods=['GET', 'POST'])\n@login_required\ndef product_images(pid):\n    product = db.get_product(pid, g.user['id'])\n    if not product:\n        flash('Not found', 'error')\n        return redirect('/')\n    if request.method == 'POST':\n        f = request.files.get('image')\n        if f and f.filename:\n            import uuid\n            upload_dir = 'static/uploads'\n            os.makedirs(upload_dir, exist_ok=True)\n            ext = f.filename.rsplit('.', 1)[-1].lower()\n            name = uuid.uuid4().hex[:12] + '.' + ext\n            f.save(os.path.join(upload_dir, name))\n            db.add_product_image(pid, name)\n            flash('Image uploaded', 'success')\n        return redirect('/product/' + str(pid) + '/images')\n    images = db.list_product_images(pid)\n    return render_template('product_images.html', product=product, images=images)\n\n\n# ============== MISSIONS (customer) ==============\n@app.route('/shop/missions')\n@customer_required\ndef customer_missions():\n    missions = db.list_missions()\n    return render_template('shop/missions.html', missions=missions)\n\n\n@app.route('/shop/missions/<int:mid>/claim', methods=['POST'])\n@customer_required\ndef mission_claim(mid):\n    flash('Mission claimed', 'success')\n    return redirect('/shop/missions')\n\n\n@app.route('/uploads/<path:filename>')\ndef uploaded_file(filename):\n    from flask import send_from_directory\n    return send_from_directory('static/uploads', filename)\n\n\n" 
content = open("web_app.py", encoding="utf-8").read() 
marker = "# ================= WEBSOCKET =================" 
if "def dashboard" not in content and marker in content: 
    content = content.replace(marker, ROUTES + marker) 
    open("web_app.py", "w", encoding="utf-8").write(content) 
    print("web_app.py updated") 
else: 
    print("web_app.py already updated or marker missing") 
print("DONE") 
